
--ecm
DROP TRIGGER CUS_QYJ_TRIGGER_LIMITS_INSERT1;
drop TRIGGER CUS_QYJ_TRIGGER_LIMITS_UPDATE1;

--ebs
DROP TRIGGER CUS_QYJ_LIMITS_ADDUSER_ZB;
DROP TRIGGER cus_qyj_limits_delUser_ZB;
DROP TRIGGER CUS_QYJ_TRIGGER_LIMITS_HT;
DROP TRIGGER CUS_QYJ_LIMITS_ADDUSER_HT;
DROP TRIGGER CUS_QYJ_LIMITS_ADDUSER_JB;
DROP TRIGGER CUS_QYJ_LIMITS_UPPSUPP_ZB;
DROP TRIGGER CUS_QYJ_LIMITS_ADDSUPP_ZB;
