
--在 ECM 的数据库中添加的trigger，,SYSTEM用户添加
--该触发器主要是当上传文件时，根据EBS中的规则写入正确的权限。
--DROP TRIGGER CUS_TRIGGER_LIMITS_INSERT;
--SELECT * FROM all_triggers WHERE table_name = 'DOCMETA';
CREATE OR REPLACE TRIGGER CUS_TRIGGER_LIMITS_INSERT
  BEFORE INSERT ON DEV1_OCS.DOCMETA
  FOR EACH ROW
DECLARE
  MYCOUNT   INT;
  DOCM_TYPE VARCHAR2(120);
  DOCM_DID  VARCHAR2(120);
  MY_ID     VARCHAR2(120);
  MY_DID       INT;
  USERNAME  VARCHAR2(600);
BEGIN  
   SELECT COUNT(1)
     INTO MYCOUNT
     FROM DEV1_OCS.REVISIONS REV, DEV1_OCS.AFOBJECTS AFO
    WHERE REV.DID = :NEW.DID
      AND REV.DDOCNAME = AFO.DDOCNAME;
    
     IF  MYCOUNT > 0  THEN
     
      SELECT DISTINCT AFO.DAFBUSINESSOBJECTTYPE, AFO.DAFBUSINESSOBJECT, UPPER(REV.DDOCAUTHOR)
        INTO DOCM_TYPE , MY_ID ,USERNAME
        FROM DEV1_OCS.REVISIONS REV, DEV1_OCS.AFOBJECTS AFO
       WHERE REV.DID = :NEW.DID
         AND REV.DDOCNAME = AFO.DDOCNAME;
         
         
      IF :NEW.XECMTEST <> 'juebiao' THEN
          IF DOCM_TYPE = 'PON_AUCTION_HEADERS_ALL' THEN
            :NEW.XCLBRAUSERLIST := APPS.CUX_QX_ECMLIMITS_PKG.CUS_FUNC_GETLIMITS_ZB@to_EBS_Dev(MY_ID,:NEW.XECMTEST);
          ELSIF DOCM_TYPE = 'PO_HEADERS_MERGE_V' OR DOCM_TYPE = 'PON_BID_HEADERS' THEN
            :NEW.XCLBRAUSERLIST := '&&' || USERNAME || '(RWDA)';
          END IF;
      ELSE
          :NEW.XCLBRAUSERLIST := '&&' || USERNAME || '(RWDA)';
      END IF;
      
    END IF;
END;

--该触发器主要是，当用户修改<招标>文件的类型时，重新设置该文件相对应的权限。
--drop TRIGGER CUS_TRIGGER_LIMITS_UPDATE
--SELECT * FROM All_Triggers v WHERE v.table_name = 'DOCMETA';
CREATE OR REPLACE TRIGGER CUS_TRIGGER_LIMITS_UPDATE
  BEFORE UPDATE ON DEV1_OCS.DOCMETA
  FOR EACH ROW
DECLARE
  MYCOUNT   INT;
  DOCM_TYPE VARCHAR2(120);
  MY_ID     VARCHAR2(120);
  USERNAME  VARCHAR2(600);
  TEMP  VARCHAR2(600);
BEGIN
  IF :NEW.XECMTEST <> :OLD.XECMTEST THEN
        SELECT COUNT(1)
          INTO MYCOUNT
          FROM DEV1_OCS.AFOBJECTS A, DEV1_OCS.REVISIONS C
         WHERE A.DDOCNAME = C.DDOCNAME
           AND C.DID = :NEW.DID;
              
        IF MYCOUNT = 1 THEN
          SELECT DISTINCT A.DAFBUSINESSOBJECTTYPE, A.DAFBUSINESSOBJECT ,UPPER(C.DDOCAUTHOR)
            INTO DOCM_TYPE , MY_ID , USERNAME
            FROM DEV1_OCS.AFOBJECTS A, DEV1_OCS.REVISIONS C
           WHERE A.DDOCNAME = C.DDOCNAME
             AND C.DID = :NEW.DID;
            
            IF DOCM_TYPE = 'PON_AUCTION_HEADERS_ALL' THEN
               IF :NEW.XECMTEST = 'juebiao' THEN          
                 TEMP := APPS.CUX_QX_ECMLIMITS_PKG.CUS_FUNC_GETLIMITS_JB@to_EBS_Dev(MY_ID);
                 IF TEMP IS NOT NULL THEN
                    :NEW.XCLBRAUSERLIST := TEMP;
                 ELSE
                    :NEW.XCLBRAUSERLIST := '&&' || USERNAME || '(RWDA)';
                 END IF;
               ELSE 
                 :NEW.XCLBRAUSERLIST := APPS.CUX_QX_ECMLIMITS_PKG.CUS_FUNC_GETLIMITS_ZB@to_EBS_Dev(MY_ID,:NEW.XECMTEST);
               END IF;
            END IF;
        END IF;
  END IF;
END;
